name = "cloudpress-system"
compatibility_date = "2024-04-01"

[env.admin]
main = "main-worker.js"
[[env.admin.d1_databases]]
binding = "cp_main_db"
database_name = "cp_main_db"
database_id = "b90bb93d-4099-4989-9302-e2c6a49cad3d"

[env.engine]
main = "site-worker.js"
[[env.engine.kv_namespaces]]
binding = "CACHE_KV"
id = "4751090f9b1a48508315558a5f91cd3b"

[[migrations]]
tag = "v1"
new_classes = ["QuotaManager", "LockManager"]
